### ISSUE TITLE
Installing jar on Ubuntu 18.04

### ISSUE THREAD

**Issue by JSchaeuble** [HuygensING/hyper-collate#48]
Hi, 
I tried to run hypercollate as a service, to access it from my eXist-db app via the REST API. I tried throwing the war into eXist's Jetty instance but it did not run and I did not know how to configure it. 

Then I tried to install the jar (for now I don't care if its running in the same jetty instance as eXist). On Windows, installing the jar is no problem, but on Windows it's rather useless for me. On my Ubuntu 18.04 development server (Java version "17" 2021-09-14 LTS) I'm getting an error:

`# java -jar hyper-collate-server.jar server
INFO  [2021-10-14 22:49:09,236] org.eclipse.jetty.util.log: Logging initialized @2527ms to org.eclipse.jetty.util.log.Slf4jLog
INFO  [2021-10-14 22:49:09,316] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2021-10-14 22:49:09,318] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
java.lang.NoSuchMethodError: 'void io.dropwizard.assets.AssetsBundle.run(io.dropwizard.Configuration, io.dropwizard.setup.Environment)'
        at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:71)
        at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:46)
        at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at nl.knaw.huygens.hypercollate.dropwizard.ServerApplication.main(ServerApplication.java:47)`

I hoped to avoid having to look into the Java code as I haven't been working in Java in some years. I would just like to play with hypercollate as a service from my eXist-db app without having to look behind the scenes too much. Do you maybe have an idea how to deploy the war via eXist's jetty **or** how to install the jar on an Ubuntu server (i.e. solve the error above)? Cheers

**Comment by brambg** [comment]
As we got no reply in the last year, we'll consider this issue solved.
